import actions from "./actions";
import mutations from "./mutations";
import getters from "./getters";

const state = {
  loadingState: false,
  sidebarList: [],
  activeObject: null,
  sidebarUserAction: null,
  activeLibrary: null,
  activeProject: null,
  activeSample: null,
  activeSite: null,
  activeSelectionSeries: null,
  activeRelatedDataTab: {},
  activeSearchParams: null,
  activeSearchParametersFilters: [],
  selection_seriesSearchParameters: {
    id: null,
    name: null,
    remarks: null,
    user_added: null,
    page: 1,
    paginateBy: 50,
    sortBy: ["id"],
    sortDesc: [true],
  },
  selection_seriesViewType: "table",
  stratigraphySearchParameters: {
    id: null,
    stratigraphy: null,
    type: null,
    rank: null,
    scope: null,
    parent: null,
    page: 1,
    paginateBy: 10,
    sortBy: ["id"],
    sortDesc: [true],
  },
  stratigraphyViewType: "table",
  isSampleSimpleView: false,
  taxonSearchParameters: {
    id: null,
    taxon: null,
    author_year: null,
    taxon_epithet: null,
    parent__taxon: null,
    selectionId: null,
    selection: null,
    page: 1,
    paginateBy: 50,
    sortBy: ["id"],
    sortDesc: [true],
  },
  taxonViewType: "table",
  rockSearchParameters: {
    name: null,
    name_en: null,
    formula: null,
    rock_type: null,
    rock_rank: null,
    in_portal: null,
    in_estonia: null,
    user_changed: null,
    page: 1,
    paginateBy: 10,
    sortBy: ["name"],
    sortDesc: [true],
  },
  rockViewType: "table",
  collectionSearchParameters: {
    id: null,
    number: null,
    name: null,
    agent: null,
    locality: null,
    reference: null,
    classification: null,
    page: 1,
    paginateBy: 50,
    sortBy: ["collection_id"],
    sortDesc: [true],
  },
  collectionViewType: "table",
  locationSearchParameters: {
    id: null,
    location: null,
    location_location: null,
    stratigraphy_free: null,
    agent: null,
    contents: null,
    page: 1,
    paginateBy: 10,
    sortBy: ["id"],
    sortDesc: [true],
  },
  locationViewType: "table",
  agentSearchParameters: {
    id: null,
    agent: null,
    forename: null,
    surename: null,
    page: 1,
    paginateBy: 50,
    sortBy: ["agent"],
    sortDesc: [false],
  },
  agentViewType: "table",
  visitSearchParameters: {
    visitor: null,
    date_arrived: null,
    date_left: null,
    page: 1,
    paginateBy: 50,
    sortBy: ["id"],
    sortDesc: [true],
  },
  visitViewType: "table",
  loanSearchParameters: {
    loan_number: null,
    project: null,
    borrower: null,
    date_start: null,
    date_end: null,
    isActive: null,
    page: 1,
    paginateBy: 50,
    sortBy: ["id"],
    sortDesc: [true],
  },
  loanViewType: "table",
  accessionSearchParameters: {
    number: null,
    description: null,
    page: 1,
    paginateBy: 50,
    sortBy: ["number"],
    sortDesc: [true],
  },
  accessionViewType: "table",
  deaccessionSearchParameters: {
    number: null,
    description: null,
    page: 1,
    paginateBy: 50,
    sortBy: ["number"],
    sortDesc: [true],
  },
  deaccessionViewType: "table",
  web_newsSearchParameters: {
    id: null,
    title: null,
    page: 1,
    paginateBy: 50,
    sortBy: ["id"],
    sortDesc: [true],
  },
  web_newsViewType: "table",
  web_pagesSearchParameters: {
    id: null,
    title: null,
    page: 1,
    paginateBy: 50,
    sortBy: ["id"],
    sortDesc: [true],
  },
  web_pagesViewType: "table",
  taxon_pageSearchParameters: {
    id: null,
    title: null,
    taxon: null,
    on_frontpage: null,
    page: 1,
    paginateBy: 50,
    sortBy: ["id"],
    sortDesc: [true],
  },
  taxon_pageViewType: "table",
  sarv_issueSearchParameters: {
    title: null,
    description: null,
    from_user: null,
    page: 1,
    paginateBy: 50,
    sortBy: ["response"],
    sortDesc: [true],
  },
  sarv_issueViewType: "table",
  activeSarvIssues: null,
  lookUpTypes: [
    //exact, iexact, in, range, contains, icontains, startswith, istartswith, endswith, iendswith, gt, lt, gte, lte, isnull, hierarchy
    { text: "main.iexact", value: "iexact", symbol: "=" },
    { text: "main.icontains", value: "icontains", symbol: "*" },
    { text: "main.istartswith", value: "istartswith", symbol: "*=" },
    { text: "main.iendswith", value: "iendswith", symbol: "*=" },
    { text: "main.gte", value: "gte", symbol: ">" },
    { text: "main.lte", value: "lte", symbol: "<" },
    { text: "main.between", value: "range", symbol: "<>" },
    { text: "main.doesnotequal", value: "iexact!", symbol: "!=" },
    { text: "main.doesnotcontain", value: "icontains!", symbol: "!*" },
    { text: "main.hierarchy", value: "hierarchy", symbol: "-·=" },
  ],
  paginateByOptions: [
    { text: "main.pagination", value: 10 },
    { text: "main.pagination", value: 25 },
    { text: "main.pagination", value: 50 },
    { text: "main.pagination", value: 100 },
    { text: "main.pagination", value: 250 },
    { text: "main.pagination", value: 500 },
    { text: "main.pagination", value: 1000 },
  ],
  activeSelectionSeriesList: null,
  activeLibraryList: null,
};

export default {
  namespaced: true,
  state,
  getters,
  actions,
  mutations,
};
