import getters from "@/store/modules/tableHeaders/getters";
import actions from "@/store/modules/tableHeaders/actions";
import mutations from "@/store/modules/tableHeaders/mutations";

// Todo: Change __ to . as vuetify support object notation in table headers (agent.id, specimen.specimen_full_name etc.)

const state = {
  accession: [
    {
      value: "number",
      text: "accession.number",
      show: true,
    },
    {
      value: "date_signed",
      text: "accession.date_signed",
      show: true,
    },
    {
      value: "agent_andis.agent",
      text: "accession.agent_andis__agent",
      show: true,
    },
    {
      value: "agent_vottis.agent",
      text: "accession.agent_vottis__agent",
      show: true,
    },
    {
      value: "number_items",
      text: "accession.number_items",
      show: true,
    },
    {
      value: "description",
      text: "accession.description",
      show: true,
    },
    {
      value: "id",
      text: "accession.id",
      show: true,
    },
    {
      value: "date_confirmed",
      text: "accession.date_confirmed",
      show: false,
    },
    {
      value: "agent_kinnitas.agent",
      text: "accession.agent_kinnitas__agent",
      show: false,
    },
    {
      value: "remarks",
      text: "accession.remarks",
      show: false,
    },
    {
      value: "user_added",
      text: "accession.user_added",
      show: false,
    },
    {
      value: "date_added",
      text: "accession.date_added",
      show: false,
    },
    {
      value: "user_changed",
      text: "accession.user_changed",
      show: false,
    },
    {
      value: "date_changed",
      text: "accession.date_changed",
      show: false,
    },
    {
      value: "database.acronym",
      text: "accession.database__acronym",
      show: false,
    },
  ],
  agent: [
    {
      value: "id",
      text: "agent.id",
      show: true,
    },
    {
      value: "agent",
      text: "agent.agent",
      show: true,
    },
    {
      value: "forename",
      text: "agent.forename",
      show: true,
    },
    {
      value: "surename",
      text: "agent.surename",
      show: true,
    },
    {
      value: "institution_name",
      text: "agent.institution_name",
      show: true,
    },
    {
      value: "remarks",
      text: "agent.remarks",
      show: true,
    },
    {
      value: "type.value",
      text: "agent.type__value",
      show: false,
    },
    {
      value: "type.value_en",
      text: "agent.type__value_en",
      show: false,
    },
    {
      value: "middlename",
      text: "agent.middlename",
      show: false,
    },
    {
      value: "title",
      text: "agent.title",
      show: false,
    },
    {
      value: "profession",
      text: "agent.profession",
      show: false,
    },
    {
      value: "profession_en",
      text: "agent.profession_en",
      show: false,
    },
    {
      value: "institution.agent",
      text: "agent.institution__agent",
      show: false,
    },
    {
      value: "institution_name_en",
      text: "agent.institution_name_en",
      show: false,
    },
    {
      value: "address",
      text: "agent.address",
      show: false,
    },
    {
      value: "address1",
      text: "agent.address1",
      show: false,
    },
    {
      value: "address2",
      text: "agent.address2",
      show: false,
    },
    {
      value: "country.value",
      text: "agent.country__value",
      show: false,
    },
    {
      value: "country.value_en",
      text: "agent.country__value_en",
      show: false,
    },
    {
      value: "country_txt",
      text: "agent.country_txt",
      show: false,
    },
    {
      value: "phone",
      text: "agent.phone",
      show: false,
    },
    {
      value: "email",
      text: "agent.email",
      show: false,
    },
    {
      value: "http",
      text: "agent.http",
      show: false,
    },
    {
      value: "old_name",
      text: "agent.old_name",
      show: false,
    },
    {
      value: "new_name",
      text: "agent.new_name",
      show: false,
    },
    {
      value: "date_born",
      text: "agent.date_born",
      show: false,
    },
    {
      value: "date_deceased",
      text: "agent.date_deceased",
      show: false,
    },
    {
      value: "orcid",
      text: "agent.orcid",
      show: false,
    },
    {
      value: "user_added",
      text: "agent.user_added",
      show: false,
    },
    {
      value: "date_added",
      text: "agent.date_added",
      show: false,
    },
    {
      value: "user_changed",
      text: "agent.user_changed",
      show: false,
    },
    {
      value: "date_changed",
      text: "agent.date_changed",
      show: false,
    },
  ],
  collection: [
    {
      value: "collection_id",
      text: "collection.collection_id",
      show: true,
    },
    {
      value: "name",
      text: "collection.name",
      show: true,
    },
    {
      value: "name_long",
      text: "collection.name_long",
      show: true,
    },
    {
      value: "database__acronym",
      text: "collection.database__acronym",
      show: true,
    },
    {
      value: "link",
      text: "collection.link",
      sortable: false,
      show: true,
    },
    {
      value: "id",
      text: "collection.id",
      show: false,
    },
    {
      value: "number",
      text: "collection.number",
      show: false,
    },
    {
      value: "name_en",
      text: "collection.name_en",
      show: false,
    },
    {
      value: "name_long_en",
      text: "collection.name_long_en",
      show: false,
    },
    {
      value: "type__id",
      text: "collection.type__id",
      show: false,
    },
    {
      value: "type__value",
      text: "collection.type__value",
      show: false,
    },
    {
      value: "type__value_en",
      text: "collection.type__value_en",
      show: false,
    },
    {
      value: "classification__id",
      text: "collection.classification__id",
      show: false,
    },
    {
      value: "classification__class_field",
      text: "collection.classification__class_field",
      show: false,
    },
    {
      value: "agent__id",
      text: "collection.agent__id",
      show: false,
    },
    {
      value: "agent__agent",
      text: "collection.agent__agent",
      show: false,
    },
    {
      value: "locality__id",
      text: "collection.locality__id",
      show: false,
    },
    {
      value: "locality__locality",
      text: "collection.locality__locality",
      show: false,
    },
    {
      value: "locality__locality_en",
      text: "collection.locality__locality_en",
      show: false,
    },
    {
      value: "stratigraphy__id",
      text: "collection.stratigraphy__id",
      show: false,
    },
    {
      value: "stratigraphy__stratigraphy",
      text: "collection.stratigraphy__stratigraphy",
      show: false,
    },
    {
      value: "stratigraphy__stratigraphy_en",
      text: "collection.stratigraphy__stratigraphy_en",
      show: false,
    },
    {
      value: "number_objects",
      text: "collection.number_objects",
      show: false,
    },
    {
      value: "number_types",
      text: "collection.number_types",
      show: false,
    },
    {
      value: "reference__id",
      text: "collection.reference__id",
      show: false,
    },
    {
      value: "reference__reference",
      text: "collection.reference__reference",
      show: false,
    },
    {
      value: "remarks",
      text: "collection.remarks",
      show: false,
    },
    {
      value: "user_added",
      text: "collection.user_added",
      show: false,
    },
    {
      value: "date_added",
      text: "collection.date_added",
      show: false,
    },
    {
      value: "user_changed",
      text: "collection.user_changed",
      show: false,
    },
    {
      value: "date_changed",
      text: "collection.date_changed",
      show: false,
    },
    {
      value: "database__id",
      text: "collection.database__id",
      show: false,
    },
  ],
  deaccession: [
    {
      value: "number",
      text: "deaccession.number",
      show: true,
    },
    {
      value: "date_signed",
      text: "deaccession.date_signed",
      show: true,
    },
    {
      value: "number_items",
      text: "deaccession.number_items",
      show: true,
    },
    {
      value: "description",
      text: "deaccession.description",
      show: true,
    },
    {
      value: "id",
      text: "deaccession.id",
      show: true,
    },
    {
      value: "date_confirmed",
      text: "deaccession.date_confirmed",
      show: false,
    },
    {
      value: "agent_kandis__agent",
      text: "deaccession.agent_kandis__agent",
      show: false,
    },
    {
      value: "agent_kandis__id",
      text: "deaccession.agent_kandis__id",
      show: false,
    },
    {
      value: "agent_kinnitas__id",
      text: "deaccession.agent_kinnitas__id",
      show: false,
    },
    {
      value: "agent_kinnitas__agent",
      text: "deaccession.agent_kinnitas__agent",
      show: false,
    },
    {
      value: "remarks",
      text: "deaccession.remarks",
      show: false,
    },
    {
      value: "user_added",
      text: "deaccession.user_added",
      show: false,
    },
    {
      value: "date_added",
      text: "deaccession.date_added",
      show: false,
    },
    {
      value: "user_changed",
      text: "deaccession.user_changed",
      show: false,
    },
    {
      value: "date_changed",
      text: "deaccession.date_changed",
      show: false,
    },
    {
      value: "database__id",
      text: "deaccession.database__id",
      show: false,
    },
    {
      value: "database__acronym",
      text: "deaccession.database__acronym",
      show: false,
    },
  ],
  loan: [
    {
      value: "print",
      text: "loan.print",
      sortable: false,
      show: true,
    },
    {
      value: "id",
      text: "loan.id",
      show: true,
    },
    {
      value: "loan_number",
      text: "loan.loan_number",
      show: true,
    },
    {
      value: "project",
      text: "loan.project",
      show: true,
    },
    {
      value: "date_start",
      text: "loan.date_start",
      show: true,
    },
    {
      value: "date_end",
      text: "loan.date_end",
      show: true,
    },
    {
      value: "returned",
      text: "loan.returned",
      show: true,
    },
    {
      value: "type__id",
      text: "loan.type__id",
      show: false,
    },
    {
      value: "type__value",
      text: "loan.type__value",
      show: false,
    },
    {
      value: "type__value_en",
      text: "loan.type__value_en",
      show: false,
    },
    {
      value: "borrower__id",
      text: "loan.borrower__id",
      show: false,
    },
    {
      value: "borrower__agent",
      text: "loan.borrower__agent",
      show: false,
    },
    {
      value: "borrower_institution",
      text: "loan.borrower_institution",
      show: false,
    },
    {
      value: "borrower_institution__agent",
      text: "loan.borrower_institution__agent",
      show: false,
    },
    {
      value: "loaner__id",
      text: "loan.loaner__id",
      show: false,
    },
    {
      value: "loaner__agent",
      text: "loan.loaner__agent",
      show: false,
    },
    {
      value: "date_signed",
      text: "loan.date_signed",
      show: false,
    },
    {
      value: "delivery_method__id",
      text: "loan.delivery_method__id",
      show: false,
    },
    {
      value: "delivery_method__value",
      text: "loan.delivery_method__value",
      show: false,
    },
    {
      value: "delivery_method__value_en",
      text: "loan.delivery_method__value_en",
      show: false,
    },
    {
      value: "deliverer__id",
      text: "loan.deliverer__id",
      show: false,
    },
    {
      value: "deliverer__agent",
      text: "loan.deliverer__agent",
      show: false,
    },
    {
      value: "delivery_remarks",
      text: "loan.delivery_remarks",
      show: false,
    },
    {
      value: "date_returned",
      text: "loan.date_returned",
      show: false,
    },
    {
      value: "special",
      text: "loan.special",
      show: false,
    },
    {
      value: "remarks",
      text: "loan.remarks",
      show: false,
    },
    {
      value: "user_added",
      text: "loan.user_added",
      show: false,
    },
    {
      value: "date_added",
      text: "loan.date_added",
      show: false,
    },
    {
      value: "user_changed",
      text: "loan.user_changed",
      show: false,
    },
    {
      value: "date_changed",
      text: "loan.date_changed",
      show: false,
    },
    {
      value: "database__id",
      text: "loan.database__id",
      show: false,
    },
    {
      value: "database__acronym",
      text: "loan.database__acronym",
      show: false,
    },
  ],
  location: [
    {
      value: "id",
      text: "location.id",
      show: true,
    },
    {
      value: "location",
      text: "location.location",
      show: true,
    },
    {
      value: "parent_location__location",
      text: "location.parent_location__location",
      show: true,
    },
    {
      value: "contents",
      text: "location.contents",
      show: true,
    },
    {
      value: "parent_location__id",
      text: "location.parent_location__id",
      show: false,
    },
    {
      value: "location_location",
      text: "location.location_location",
      show: false,
    },
    {
      value: "agent__id",
      text: "location.agent__id",
      show: false,
    },
    {
      value: "agent__agent",
      text: "location.agent__agent",
      show: false,
    },
    {
      value: "date_collected_free",
      text: "location.date_collected_free",
      show: false,
    },
    {
      value: "stratigraphy_free",
      text: "location.stratigraphy_free",
      show: false,
    },
    {
      value: "number_items",
      text: "location.number_items",
      show: false,
    },
    {
      value: "number_items_registered",
      text: "location.number_items_registered",
      show: false,
    },
    {
      value: "remarks",
      text: "location.remarks",
      show: false,
    },
    {
      value: "database__id",
      text: "location.database__id",
      show: false,
    },
    {
      value: "database__acronym",
      text: "location.database__acronym",
      show: false,
    },
    {
      value: "user_added",
      text: "location.user_added",
      show: false,
    },
    {
      value: "date_added",
      text: "location.date_added",
      show: false,
    },
    {
      value: "user_changed",
      text: "location.user_changed",
      show: false,
    },
    {
      value: "date_changed",
      text: "location.date_changed",
      show: false,
    },
  ],
  rock: [
    {
      value: "id",
      text: "rock.id",
      show: true,
    },
    {
      value: "name",
      text: "rock.name",
      show: true,
    },
    {
      value: "name_en",
      text: "rock.name_en",
      show: true,
    },
    {
      value: "formula_html",
      text: "rock.formula_html",
      show: true,
    },
    {
      value: "in_estonia",
      text: "rock.in_estonia",
      show: true,
    },
    {
      value: "in_portal",
      text: "rock.in_portal",
      show: true,
    },
    {
      value: "link",
      text: "rock.link",
      sortable: false,
      show: true,
    },
    {
      value: "mindat_id",
      text: "rock.mindat_id",
      show: true,
    },
    {
      value: "name_ru",
      text: "rock.name_ru",
      show: false,
    },
    {
      value: "rock_type__id",
      text: "rock.rock_type__id",
      show: false,
    },
    {
      value: "rock_type__name",
      text: "rock.rock_type__name",
      show: false,
    },
    {
      value: "rock_type__name_en",
      text: "rock.rock_type__name_en",
      show: false,
    },
    {
      value: "rock_rank__id",
      text: "rock.rock_rank__id",
      show: false,
    },
    {
      value: "rock_rank__name",
      text: "rock.rock_rank__name",
      show: false,
    },
    {
      value: "rock_rank__name_en",
      text: "rock.rock_rank__name_en",
      show: false,
    },
    {
      value: "parent__id",
      text: "rock.parent__id",
      show: false,
    },
    {
      value: "parent__name",
      text: "rock.parent__name",
      show: false,
    },
    {
      value: "parent__name_en",
      text: "rock.parent__name_en",
      show: false,
    },
    {
      value: "synonym_of__id",
      text: "rock.synonym_of__id",
      show: false,
    },
    {
      value: "synonym_of__name",
      text: "rock.synonym_of__name",
      show: false,
    },
    {
      value: "synonym_of__name_en",
      text: "rock.synonym_of__name_en",
      show: false,
    },
    {
      value: "sort",
      text: "rock.sort",
      show: false,
    },
    {
      value: "description",
      text: "rock.description",
      show: false,
    },
    {
      value: "description_en",
      text: "rock.description_en",
      show: false,
    },
    {
      value: "description_ru",
      text: "rock.description_ru",
      show: false,
    },
    {
      value: "description_in_estonia",
      text: "rock.description_in_estonia",
      show: false,
    },
    {
      value: "description_in_estonia_en",
      text: "rock.description_in_estonia_en",
      show: false,
    },
    {
      value: "description_in_estonia_ru",
      text: "rock.description_in_estonia_ru",
      show: false,
    },
    {
      value: "description_usage",
      text: "rock.description_usage",
      show: false,
    },
    {
      value: "description_usage_en",
      text: "rock.description_usage_en",
      show: false,
    },
    {
      value: "description_usage_ru",
      text: "rock.description_usage_ru",
      show: false,
    },
    {
      value: "description_author",
      text: "rock.description_author",
      show: false,
    },
    {
      value: "is_resource",
      text: "rock.is_resource",
      show: false,
    },
    {
      value: "stratigraphy__id",
      text: "rock.stratigraphy__id",
      show: false,
    },
    {
      value: "stratigraphy__stratigraphy",
      text: "rock.stratigraphy__stratigraphy",
      show: false,
    },
    {
      value: "stratigraphy__stratigraphy_en",
      text: "rock.stratigraphy__stratigraphy_en",
      show: false,
    },
    {
      value: "lithostratigraphy__id",
      text: "rock.lithostratigraphy__id",
      show: false,
    },
    {
      value: "lithostratigraphy__stratigraphy",
      text: "rock.lithostratigraphy__stratigraphy",
      show: false,
    },
    {
      value: "lithostratigraphy__stratigraphy_en",
      text: "rock.lithostratigraphy__stratigraphy_en",
      show: false,
    },
    {
      value: "link_wikipedia",
      text: "rock.link_wikipedia",
      show: false,
    },
    {
      value: "link_wikipedia_en",
      text: "rock.link_wikipedia_en",
      show: false,
    },
    {
      value: "link_wikipedia_ru",
      text: "rock.link_wikipedia_ru",
      show: false,
    },
    {
      value: "ima_status",
      text: "rock.ima_status",
      show: false,
    },
    {
      value: "formula",
      text: "rock.formula",
      show: false,
    },
    {
      value: "remarks",
      text: "rock.remarks",
      show: false,
    },
    {
      value: "is_private",
      text: "rock.is_private",
      show: false,
    },
    {
      value: "user_added",
      text: "rock.user_added",
      show: false,
    },
    {
      value: "date_added",
      text: "rock.date_added",
      show: false,
    },
    {
      value: "user_changed",
      text: "rock.user_changed",
      show: false,
    },
    {
      value: "date_changed",
      text: "rock.date_changed",
      show: false,
    },
  ],
  sarv_issue: [
    {
      value: "replied",
      text: "sarv_issue.replied",
      sortable: false,
      show: true,
    },
    {
      value: "date_added",
      text: "sarv_issue.date_added",
      show: true,
    },
    {
      value: "to_user__username",
      text: "sarv_issue.to_user__username",
      show: true,
    },
    {
      value: "title",
      text: "sarv_issue.title",
      show: true,
    },
    {
      value: "description",
      text: "sarv_issue.description",
      show: true,
    },
    {
      value: "url",
      text: "sarv_issue.url",
      show: true,
    },
    {
      value: "response",
      text: "sarv_issue.response",
      show: true,
    },
    {
      value: "from_user__id",
      text: "sarv_issue.from_user__id",
      show: false,
    },
    {
      value: "to_user__id",
      text: "sarv_issue.to_user__id",
      show: false,
    },
    {
      value: "user_added",
      text: "sarv_issue.user_added",
      show: false,
    },
    {
      value: "user_changed",
      text: "sarv_issue.user_changed",
      show: false,
    },
    {
      value: "date_changed",
      text: "sarv_issue.date_changed",
      show: false,
    },
    {
      value: "idfrom_user__username",
      text: "sarv_issue.idfrom_user__username",
      show: false,
    },
  ],
  selection_series: [
    {
      value: "id",
      text: "selection_series.id",
      show: true,
    },
    {
      value: "name",
      text: "selection_series.name",
      show: true,
    },
    {
      value: "remarks",
      text: "selection_series.remarks",
      show: true,
    },
    {
      value: "user_added",
      text: "selection_series.user_added",
      show: true,
    },
    {
      value: "tablename",
      text: "selection_series.tablename",
      show: false,
    },
    {
      value: "date_added",
      text: "selection_series.date_added",
      show: false,
    },
    {
      value: "user_changed",
      text: "selection_series.user_changed",
      show: false,
    },
    {
      value: "date_changed",
      text: "selection_series.date_changed",
      show: false,
    },
    {
      value: "database__id",
      text: "selection_series.database__id",
      show: false,
    },
    {
      value: "database__acronym",
      text: "selection_series.database__acronym",
      show: false,
    },
  ],
  stratigraphy: [
    {
      value: "id",
      text: "stratigraphy.id",
      show: true,
    },
    {
      value: "stratigraphy",
      text: "stratigraphy.stratigraphy",
      show: true,
    },
    {
      value: "link",
      text: "stratigraphy.link",
      sortable: false,
      show: true,
    },
    {
      value: "stratigraphy_en",
      text: "stratigraphy.stratigraphy_en",
      show: false,
    },
    {
      value: "stratigraphy_original",
      text: "stratigraphy.stratigraphy_original",
      show: false,
    },
    {
      value: "author_free",
      text: "stratigraphy.author_free",
      show: false,
    },
    {
      value: "year",
      text: "stratigraphy.year",
      show: false,
    },
    {
      value: "etymon",
      text: "stratigraphy.etymon",
      show: false,
    },
    {
      value: "etymon_en",
      text: "stratigraphy.etymon_en",
      show: false,
    },
    {
      value: "original_locality",
      text: "stratigraphy.original_locality",
      show: false,
    },
    {
      value: "original_rank",
      text: "stratigraphy.original_rank",
      show: false,
    },
    {
      value: "index_main",
      text: "stratigraphy.index_main",
      show: false,
    },
    {
      value: "index_main_html",
      text: "stratigraphy.index_main_html",
      show: false,
    },
    {
      value: "index_additional",
      text: "stratigraphy.index_additional",
      show: false,
    },
    {
      value: "index_additional_html",
      text: "stratigraphy.index_additional_html",
      show: false,
    },
    {
      value: "index_old",
      text: "stratigraphy.index_old",
      show: false,
    },
    {
      value: "color_code_cgmw",
      text: "stratigraphy.color_code_cgmw",
      show: false,
    },
    {
      value: "color_code_additional",
      text: "stratigraphy.color_code_additional",
      show: false,
    },
    {
      value: "hierarchy_string",
      text: "stratigraphy.hierarchy_string",
      show: false,
    },
    {
      value: "parent__id",
      text: "stratigraphy.parent__id",
      show: false,
    },
    {
      value: "parent__stratigraphy",
      text: "stratigraphy.parent__stratigraphy",
      show: false,
    },
    {
      value: "parent__stratigraphy_en",
      text: "stratigraphy.parent__stratigraphy_en",
      show: false,
    },
    {
      value: "type__id",
      text: "stratigraphy.type__id",
      show: false,
    },
    {
      value: "type__value",
      text: "stratigraphy.type__value",
      show: false,
    },
    {
      value: "type__value_en",
      text: "stratigraphy.type__value_en",
      show: false,
    },
    {
      value: "rank__id",
      text: "stratigraphy.rank__id",
      show: false,
    },
    {
      value: "rank__value",
      text: "stratigraphy.rank__value",
      show: false,
    },
    {
      value: "rank__value_en",
      text: "stratigraphy.rank__value_en",
      show: false,
    },
    {
      value: "scope__id",
      text: "stratigraphy.scope__id",
      show: false,
    },
    {
      value: "scope__value",
      text: "stratigraphy.scope__value",
      show: false,
    },
    {
      value: "scope__value_en",
      text: "stratigraphy.scope__value_en",
      show: false,
    },
    {
      value: "status__id",
      text: "stratigraphy.status__id",
      show: false,
    },
    {
      value: "status__value",
      text: "stratigraphy.status__value",
      show: false,
    },
    {
      value: "status__value_en",
      text: "stratigraphy.status__value_en",
      show: false,
    },
    {
      value: "region",
      text: "stratigraphy.region",
      show: false,
    },
    {
      value: "region_en",
      text: "stratigraphy.region_en",
      show: false,
    },
    {
      value: "lithology",
      text: "stratigraphy.lithology",
      show: false,
    },
    {
      value: "lithology_en",
      text: "stratigraphy.lithology_en",
      show: false,
    },
    {
      value: "max_thickness",
      text: "stratigraphy.max_thickness",
      show: false,
    },
    {
      value: "description",
      text: "stratigraphy.description",
      show: false,
    },
    {
      value: "description_en",
      text: "stratigraphy.description_en",
      show: false,
    },
    {
      value: "definition",
      text: "stratigraphy.definition",
      show: false,
    },
    {
      value: "definition_en",
      text: "stratigraphy.definition_en",
      show: false,
    },
    {
      value: "age_base",
      text: "stratigraphy.age_base",
      show: false,
    },
    {
      value: "age_top",
      text: "stratigraphy.age_top",
      show: false,
    },
    {
      value: "age_precision",
      text: "stratigraphy.age_precision",
      show: false,
    },
    {
      value: "age_reference__id",
      text: "stratigraphy.age_reference__id",
      show: false,
    },
    {
      value: "age_reference__reference",
      text: "stratigraphy.age_reference__reference",
      show: false,
    },
    {
      value: "age_chronostratigraphy__id",
      text: "stratigraphy.age_chronostratigraphy__id",
      show: false,
    },
    {
      value: "age_chronostratigraphy__stratigraphy",
      text: "stratigraphy.age_chronostratigraphy__stratigraphy",
      show: false,
    },
    {
      value: "age_chronostratigraphy__stratigraphy_en",
      text: "stratigraphy.age_chronostratigraphy__stratigraphy_en",
      show: false,
    },
    {
      value: "sort_within_parent",
      text: "stratigraphy.sort_within_parent",
      show: false,
    },
    {
      value: "approved_ics",
      text: "stratigraphy.approved_ics",
      show: false,
    },
    {
      value: "approved_esk",
      text: "stratigraphy.approved_esk",
      show: false,
    },
    {
      value: "maaamet_kood",
      text: "stratigraphy.maaamet_kood",
      show: false,
    },
    {
      value: "is_private",
      text: "stratigraphy.is_private",
      show: false,
    },
    {
      value: "remarks",
      text: "stratigraphy.remarks",
      show: false,
    },
    {
      value: "user_added",
      text: "stratigraphy.user_added",
      show: false,
    },
    {
      value: "date_added",
      text: "stratigraphy.date_added",
      show: false,
    },
    {
      value: "user_changed",
      text: "stratigraphy.user_changed",
      show: false,
    },
    {
      value: "date_changed",
      text: "stratigraphy.date_changed",
      show: false,
    },
  ],
  taxon: [
    {
      value: "id",
      text: "taxon.id",
      show: true,
    },
    {
      value: "taxon",
      text: "taxon.taxon",
      show: true,
    },
    {
      value: "author_year",
      text: "taxon.author_year",
      show: true,
    },
    {
      value: "taxon_epithet",
      text: "taxon.taxon_epithet",
      show: true,
    },
    {
      value: "parent__taxon",
      text: "taxon.parent__taxon",
      show: true,
    },
    {
      value: "fossil_group__taxon",
      text: "taxon.fossil_group__taxon",
      show: true,
    },
    {
      value: "link",
      text: "taxon.link",
      sortable: false,
      show: true,
    },
    {
      value: "taxon_full_name",
      text: "taxon.taxon_full_name",
      show: false,
    },
    {
      value: "taxon_original_name",
      text: "taxon.taxon_original_name",
      show: false,
    },
    {
      value: "reference__id",
      text: "taxon.reference__id",
      show: false,
    },
    {
      value: "reference__reference",
      text: "taxon.reference__reference",
      show: false,
    },
    {
      value: "parent__id",
      text: "taxon.parent__id",
      show: false,
    },
    {
      value: "fossil_group__id",
      text: "taxon.fossil_group__id",
      show: false,
    },
    {
      value: "synonym_of",
      text: "taxon.synonym_of",
      show: false,
    },
    {
      value: "synonym_of_reference_id",
      text: "taxon.synonym_of_reference_id",
      show: false,
    },
    {
      value: "hierarchy_string",
      text: "taxon.hierarchy_string",
      show: false,
    },
    {
      value: "rank__id",
      text: "taxon.rank__id",
      show: false,
    },
    {
      value: "rank__rank",
      text: "taxon.rank__rank",
      show: false,
    },
    {
      value: "rank_original__id",
      text: "taxon.rank_original__id",
      show: false,
    },
    {
      value: "rank_original__rank",
      text: "taxon.rank_original__rank",
      show: false,
    },
    {
      value: "type_taxon__id",
      text: "taxon.type_taxon__id",
      show: false,
    },
    {
      value: "type_taxon__taxon",
      text: "taxon.type_taxon__taxon",
      show: false,
    },
    {
      value: "type_taxon_txt",
      text: "taxon.type_taxon_txt",
      show: false,
    },
    {
      value: "stratigraphy_base__id",
      text: "taxon.stratigraphy_base__id",
      show: false,
    },
    {
      value: "stratigraphy_base__stratigraphy",
      text: "taxon.stratigraphy_base__stratigraphy",
      show: false,
    },
    {
      value: "stratigraphy_base__stratigraphy_en",
      text: "taxon.stratigraphy_base__stratigraphy_en",
      show: false,
    },
    {
      value: "stratigraphy_top__id",
      text: "taxon.stratigraphy_top__id",
      show: false,
    },
    {
      value: "stratigraphy_top__stratigraphy",
      text: "taxon.stratigraphy_top__stratigraphy",
      show: false,
    },
    {
      value: "stratigraphy_top__stratigraphy_en",
      text: "taxon.stratigraphy_top__stratigraphy_en",
      show: false,
    },
    {
      value: "in_estonia",
      text: "taxon.in_estonia",
      show: false,
    },
    {
      value: "in_baltoscandia",
      text: "taxon.in_baltoscandia",
      show: false,
    },
    {
      value: "is_fossil",
      text: "taxon.is_fossil",
      show: false,
    },
    {
      value: "is_private",
      text: "taxon.is_private",
      show: false,
    },
    {
      value: "is_valid",
      text: "taxon.is_valid",
      show: false,
    },
    {
      value: "is_fossil_group",
      text: "taxon.is_fossil_group",
      show: false,
    },
    {
      value: "sort",
      text: "taxon.sort",
      show: false,
    },
    {
      value: "taxon_id_pbdb",
      text: "taxon.taxon_id_pbdb",
      show: false,
    },
    {
      value: "taxon_id_plutof",
      text: "taxon.taxon_id_plutof",
      show: false,
    },
    {
      value: "taxon_id_tol",
      text: "taxon.taxon_id_tol",
      show: false,
    },
    {
      value: "taxon_id_eol",
      text: "taxon.taxon_id_eol",
      show: false,
    },
    {
      value: "taxon_id_nrm",
      text: "taxon.taxon_id_nrm",
      show: false,
    },
    {
      value: "remarks",
      text: "taxon.remarks",
      show: false,
    },
    {
      value: "owner",
      text: "taxon.owner",
      show: false,
    },
    {
      value: "is_authorized",
      text: "taxon.is_authorized",
      show: false,
    },
    {
      value: "user_authorized",
      text: "taxon.user_authorized",
      show: false,
    },
    {
      value: "user_added",
      text: "taxon.user_added",
      show: false,
    },
    {
      value: "date_added",
      text: "taxon.date_added",
      show: false,
    },
    {
      value: "user_changed",
      text: "taxon.user_changed",
      show: false,
    },
    {
      value: "date_changed",
      text: "taxon.date_changed",
      show: false,
    },
  ],
  taxon_page: [
    {
      value: "id",
      text: "taxon_page.id",
      show: true,
    },
    {
      value: "language",
      text: "taxon_page.language",
      show: true,
    },
    {
      value: "title",
      text: "taxon_page.title",
      show: true,
    },
    {
      value: "taxon__id",
      text: "taxon_page.taxon__id",
      show: false,
    },
    {
      value: "taxon__taxon",
      text: "taxon_page.taxon__taxon",
      show: false,
    },
    {
      value: "on_frontpage",
      text: "taxon_page.on_frontpage",
      show: false,
    },
    {
      value: "frontpage",
      text: "taxon_page.frontpage",
      show: false,
    },
    {
      value: "frontpage_order",
      text: "taxon_page.frontpage_order",
      show: false,
    },
    {
      value: "frontpage_title",
      text: "taxon_page.frontpage_title",
      show: false,
    },
    {
      value: "content",
      text: "taxon_page.content",
      show: false,
    },
    {
      value: "author__id",
      text: "taxon_page.author__id",
      show: false,
    },
    {
      value: "author__agent",
      text: "taxon_page.author__agent",
      show: false,
    },
    {
      value: "author_txt",
      text: "taxon_page.author_txt",
      show: false,
    },
    {
      value: "date_txt",
      text: "taxon_page.date_txt",
      show: false,
    },
    {
      value: "is_private",
      text: "taxon_page.is_private",
      show: false,
    },
    {
      value: "link_wikipedia",
      text: "taxon_page.link_wikipedia",
      show: false,
    },
    {
      value: "user_added",
      text: "taxon_page.user_added",
      show: false,
    },
    {
      value: "date_added",
      text: "taxon_page.date_added",
      show: false,
    },
    {
      value: "user_changed",
      text: "taxon_page.user_changed",
      show: false,
    },
    {
      value: "date_changed",
      text: "taxon_page.date_changed",
      show: false,
    },
  ],
  visit: [
    {
      value: "id",
      text: "visit.id",
      show: true,
    },
    {
      value: "date_arrived",
      text: "visit.date_arrived",
      show: true,
    },
    {
      value: "date_left",
      text: "visit.date_left",
      show: true,
    },
    {
      value: "visitor__id",
      text: "visit.visitor__id",
      show: false,
    },
    {
      value: "visitor__agent",
      text: "visit.visitor__agent",
      show: false,
    },
    {
      value: "visitor_free",
      text: "visit.visitor_free",
      show: false,
    },
    {
      value: "visitor_institution__id",
      text: "visit.visitor_institution__id",
      show: false,
    },
    {
      value: "visitor_institution__agent",
      text: "visit.visitor_institution__agent",
      show: false,
    },
    {
      value: "visitor_country__id",
      text: "visit.visitor_country__id",
      show: false,
    },
    {
      value: "visitor_country__value",
      text: "visit.visitor_country__value",
      show: false,
    },
    {
      value: "visitor_country__value_en",
      text: "visit.visitor_country__value_en",
      show: false,
    },
    {
      value: "host__id",
      text: "visit.host__id",
      show: false,
    },
    {
      value: "host__agent",
      text: "visit.host__agent",
      show: false,
    },
    {
      value: "purpose",
      text: "visit.purpose",
      show: false,
    },
    {
      value: "collections_studied",
      text: "visit.collections_studied",
      show: false,
    },
    {
      value: "items_studied",
      text: "visit.items_studied",
      show: false,
    },
    {
      value: "remarks",
      text: "visit.remarks",
      show: false,
    },
    {
      value: "database__id",
      text: "visit.database__id",
      show: false,
    },
    {
      value: "database__acronym",
      text: "visit.database__acronym",
      show: false,
    },
    {
      value: "user_added",
      text: "visit.user_added",
      show: false,
    },
    {
      value: "date_added",
      text: "visit.date_added",
      show: false,
    },
    {
      value: "user_changed",
      text: "visit.user_changed",
      show: false,
    },
    {
      value: "date_changed",
      text: "visit.date_changed",
      show: false,
    },
  ],
  web_news: [
    {
      value: "id",
      text: "web_news.id",
      show: true,
    },
    {
      value: "is_private",
      text: "web_news.is_private",
      show: true,
    },
    {
      value: "title_et",
      text: "web_news.title_et",
      show: false,
    },
    {
      value: "title_en",
      text: "web_news.title_en",
      show: false,
    },
    {
      value: "text_en",
      text: "web_news.text_en",
      show: false,
    },
    {
      value: "text_et",
      text: "web_news.text_et",
      show: false,
    },
    {
      value: "user_added",
      text: "web_news.user_added",
      show: false,
    },
    {
      value: "date_added",
      text: "web_news.date_added",
      show: false,
    },
    {
      value: "user_changed",
      text: "web_news.user_changed",
      show: false,
    },
    {
      value: "date_changed",
      text: "web_news.date_changed",
      show: false,
    },
    {
      value: "date_expires",
      text: "web_news.date_expires",
      show: false,
    },
    {
      value: "timestamp",
      text: "web_news.timestamp",
      show: false,
    },
  ],
  web_pages: [
    {
      value: "id",
      text: "web_pages.id",
      show: true,
    },
    {
      value: "site",
      text: "web_pages.site",
      show: true,
    },
    {
      value: "public",
      text: "web_pages.public",
      show: true,
    },
    {
      value: "title_et",
      text: "web_pages.title_et",
      show: false,
    },
    {
      value: "menu_title_et",
      text: "web_pages.menu_title_et",
      show: false,
    },
    {
      value: "content_et",
      text: "web_pages.content_et",
      show: false,
    },
    {
      value: "link_et",
      text: "web_pages.link_et",
      show: false,
    },
    {
      value: "title_en",
      text: "web_pages.title_en",
      show: false,
    },
    {
      value: "menu_title_en",
      text: "web_pages.menu_title_en",
      show: false,
    },
    {
      value: "content_en",
      text: "web_pages.content_en",
      show: false,
    },
    {
      value: "link_en",
      text: "web_pages.link_en",
      show: false,
    },
    {
      value: "menu",
      text: "web_pages.menu",
      show: false,
    },
    {
      value: "menu_bold",
      text: "web_pages.menu_bold",
      show: false,
    },
    {
      value: "menu_color",
      text: "web_pages.menu_color",
      show: false,
    },
    {
      value: "menu_fold",
      text: "web_pages.menu_fold",
      show: false,
    },
    {
      value: "sort",
      text: "web_pages.sort",
      show: false,
    },
    {
      value: "parent",
      text: "web_pages.parent",
      show: false,
    },
    {
      value: "is_private",
      text: "web_pages.is_private",
      show: false,
    },
    {
      value: "user",
      text: "web_pages.user",
      show: false,
    },
    {
      value: "date_inserted",
      text: "web_pages.date_inserted",
      show: false,
    },
    {
      value: "date_expires",
      text: "web_pages.date_expires",
      show: false,
    },
    {
      value: "timestamp",
      text: "web_pages.timestamp",
      show: false,
    },
  ],
  searchFields: {
    accession: [
      {
        id: "number",
        title: "accession.number",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_signed",
        title: "accession.date_signed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_confirmed",
        title: "accession.date_confirmed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "agent_andis__id",
        title: "accession.agent_andis__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "agent_vottis__id",
        title: "accession.agent_vottis__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "agent_kinnitas__id",
        title: "accession.agent_kinnitas__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "number_items",
        title: "accession.number_items",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "description",
        title: "accession.description",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "remarks",
        title: "accession.remarks",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_added",
        title: "accession.user_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_added",
        title: "accession.date_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_changed",
        title: "accession.user_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_changed",
        title: "accession.date_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "database__id",
        title: "accession.database__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "id",
        title: "accession.id",
        value: null,
        lookUpType: "icontains",
      },
    ],
    agent: [
      {
        id: "agent",
        title: "agent.agent",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "type__id",
        title: "agent.type__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "forename",
        title: "agent.forename",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "middlename",
        title: "agent.middlename",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "surename",
        title: "agent.surename",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "title",
        title: "agent.title",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "profession",
        title: "agent.profession",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "profession_en",
        title: "agent.profession_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "institution__id",
        title: "agent.institution__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "institution_name",
        title: "agent.institution_name",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "institution_name_en",
        title: "agent.institution_name_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "address",
        title: "agent.address",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "address1",
        title: "agent.address1",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "address2",
        title: "agent.address2",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "country__id",
        title: "agent.country__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "country_txt",
        title: "agent.country_txt",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "phone",
        title: "agent.phone",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "email",
        title: "agent.email",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "http",
        title: "agent.http",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "old_name",
        title: "agent.old_name",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "new_name",
        title: "agent.new_name",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_born",
        title: "agent.date_born",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_deceased",
        title: "agent.date_deceased",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "orcid",
        title: "agent.orcid",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "remarks",
        title: "agent.remarks",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_added",
        title: "agent.user_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_added",
        title: "agent.date_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_changed",
        title: "agent.user_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_changed",
        title: "agent.date_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "id",
        title: "agent.id",
        value: null,
        lookUpType: "icontains",
      },
    ],
    collection: [
      {
        id: "number",
        title: "collection.number",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "collection_id",
        title: "collection.collection_id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "name",
        title: "collection.name",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "name_long",
        title: "collection.name_long",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "name_en",
        title: "collection.name_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "name_long_en",
        title: "collection.name_long_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "type__id",
        title: "collection.type__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "classification__id",
        title: "collection.classification__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "agent__id",
        title: "collection.agent__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "locality__id",
        title: "collection.locality__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "stratigraphy__id",
        title: "collection.stratigraphy__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "number_objects",
        title: "collection.number_objects",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "number_types",
        title: "collection.number_types",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "reference__id",
        title: "collection.reference__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "remarks",
        title: "collection.remarks",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_added",
        title: "collection.user_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_added",
        title: "collection.date_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_changed",
        title: "collection.user_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_changed",
        title: "collection.date_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "database__id",
        title: "collection.database__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "id",
        title: "collection.id",
        value: null,
        lookUpType: "icontains",
      },
    ],
    deaccession: [
      {
        id: "number",
        title: "deaccession.number",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_signed",
        title: "deaccession.date_signed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_confirmed",
        title: "deaccession.date_confirmed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "agent_kandis__id",
        title: "deaccession.agent_kandis__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "agent_kinnitas__id",
        title: "deaccession.agent_kinnitas__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "number_items",
        title: "deaccession.number_items",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "description",
        title: "deaccession.description",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "remarks",
        title: "deaccession.remarks",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_added",
        title: "deaccession.user_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_added",
        title: "deaccession.date_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_changed",
        title: "deaccession.user_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_changed",
        title: "deaccession.date_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "database__id",
        title: "deaccession.database__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "id",
        title: "deaccession.id",
        value: null,
        lookUpType: "icontains",
      },
    ],
    loan: [
      {
        id: "loan_number",
        title: "loan.loan_number",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_start",
        title: "loan.date_start",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_end",
        title: "loan.date_end",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "type__id",
        title: "loan.type__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "project",
        title: "loan.project",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "borrower__id",
        title: "loan.borrower__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "borrower_institution__id",
        title: "loan.borrower_institution__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "loaner__id",
        title: "loan.loaner__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_signed",
        title: "loan.date_signed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "delivery_method__id",
        title: "loan.delivery_method__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "deliverer__id",
        title: "loan.deliverer__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "delivery_remarks",
        title: "loan.delivery_remarks",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "returned",
        title: "loan.returned",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_returned",
        title: "loan.date_returned",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "special",
        title: "loan.special",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "remarks",
        title: "loan.remarks",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_added",
        title: "loan.user_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_added",
        title: "loan.date_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_changed",
        title: "loan.user_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_changed",
        title: "loan.date_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "database__id",
        title: "loan.database__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "id",
        title: "loan.id",
        value: null,
        lookUpType: "icontains",
      },
    ],
    location: [
      {
        id: "location",
        title: "location.location",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "parent_location__id",
        title: "location.parent_location__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "location_location",
        title: "location.location_location",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "contents",
        title: "location.contents",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "agent__id",
        title: "location.agent__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_collected_free",
        title: "location.date_collected_free",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "stratigraphy_free",
        title: "location.stratigraphy_free",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "number_items",
        title: "location.number_items",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "number_items_registered",
        title: "location.number_items_registered",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "remarks",
        title: "location.remarks",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "database__id",
        title: "location.database__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_added",
        title: "location.user_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_added",
        title: "location.date_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_changed",
        title: "location.user_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_changed",
        title: "location.date_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "id",
        title: "location.id",
        value: null,
        lookUpType: "icontains",
      },
    ],
    rock: [
      {
        id: "name",
        title: "rock.name",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "name_en",
        title: "rock.name_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "name_ru",
        title: "rock.name_ru",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "rock_type__id",
        title: "rock.rock_type__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "rock_rank__id",
        title: "rock.rock_rank__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "parent__id",
        title: "rock.parent__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "synonym_of__id",
        title: "rock.synonym_of__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "sort",
        title: "rock.sort",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "description",
        title: "rock.description",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "description_en",
        title: "rock.description_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "description_ru",
        title: "rock.description_ru",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "description_in_estonia",
        title: "rock.description_in_estonia",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "description_in_estonia_en",
        title: "rock.description_in_estonia_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "description_in_estonia_ru",
        title: "rock.description_in_estonia_ru",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "description_usage",
        title: "rock.description_usage",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "description_usage_en",
        title: "rock.description_usage_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "description_usage_ru",
        title: "rock.description_usage_ru",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "description_author",
        title: "rock.description_author",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "in_estonia",
        title: "rock.in_estonia",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "is_resource",
        title: "rock.is_resource",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "stratigraphy__id",
        title: "rock.stratigraphy__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "lithostratigraphy__id",
        title: "rock.lithostratigraphy__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "mindat_id",
        title: "rock.mindat_id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "link_wikipedia",
        title: "rock.link_wikipedia",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "link_wikipedia_en",
        title: "rock.link_wikipedia_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "link_wikipedia_ru",
        title: "rock.link_wikipedia_ru",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "ima_status",
        title: "rock.ima_status",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "formula",
        title: "rock.formula",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "formula_html",
        title: "rock.formula_html",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "remarks",
        title: "rock.remarks",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "is_private",
        title: "rock.is_private",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "in_portal",
        title: "rock.in_portal",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_added",
        title: "rock.user_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_added",
        title: "rock.date_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_changed",
        title: "rock.user_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_changed",
        title: "rock.date_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "id",
        title: "rock.id",
        value: null,
        lookUpType: "icontains",
      },
    ],
    sarv_issue: [
      {
        id: "title",
        title: "sarv_issue.title",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "description",
        title: "sarv_issue.description",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "url",
        title: "sarv_issue.url",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "from_user__id",
        title: "sarv_issue.from_user__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "to_user__id",
        title: "sarv_issue.to_user__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "response",
        title: "sarv_issue.response",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_added",
        title: "sarv_issue.user_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_added",
        title: "sarv_issue.date_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_changed",
        title: "sarv_issue.user_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_changed",
        title: "sarv_issue.date_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "id",
        title: "sarv_issue.id",
        value: null,
        lookUpType: "icontains",
      },
    ],
    selection_series: [
      {
        id: "name",
        title: "selection_series.name",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "tablename",
        title: "selection_series.tablename",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "remarks",
        title: "selection_series.remarks",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_added",
        title: "selection_series.user_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_added",
        title: "selection_series.date_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_changed",
        title: "selection_series.user_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_changed",
        title: "selection_series.date_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "database__id",
        title: "selection_series.database__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "id",
        title: "selection_series.id",
        value: null,
        lookUpType: "icontains",
      },
    ],
    stratigraphy: [
      {
        id: "stratigraphy",
        title: "stratigraphy.stratigraphy",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "stratigraphy_en",
        title: "stratigraphy.stratigraphy_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "stratigraphy_original",
        title: "stratigraphy.stratigraphy_original",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "author_free",
        title: "stratigraphy.author_free",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "year",
        title: "stratigraphy.year",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "etymon",
        title: "stratigraphy.etymon",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "etymon_en",
        title: "stratigraphy.etymon_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "original_locality",
        title: "stratigraphy.original_locality",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "original_rank",
        title: "stratigraphy.original_rank",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "index_main",
        title: "stratigraphy.index_main",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "index_main_html",
        title: "stratigraphy.index_main_html",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "index_additional",
        title: "stratigraphy.index_additional",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "index_additional_html",
        title: "stratigraphy.index_additional_html",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "index_old",
        title: "stratigraphy.index_old",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "color_code_cgmw",
        title: "stratigraphy.color_code_cgmw",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "color_code_additional",
        title: "stratigraphy.color_code_additional",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "hierarchy_string",
        title: "stratigraphy.hierarchy_string",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "parent__id",
        title: "stratigraphy.parent__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "type__id",
        title: "stratigraphy.type__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "rank__id",
        title: "stratigraphy.rank__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "scope__id",
        title: "stratigraphy.scope__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "status__id",
        title: "stratigraphy.status__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "region",
        title: "stratigraphy.region",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "region_en",
        title: "stratigraphy.region_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "lithology",
        title: "stratigraphy.lithology",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "lithology_en",
        title: "stratigraphy.lithology_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "max_thickness",
        title: "stratigraphy.max_thickness",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "description",
        title: "stratigraphy.description",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "description_en",
        title: "stratigraphy.description_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "definition",
        title: "stratigraphy.definition",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "definition_en",
        title: "stratigraphy.definition_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "age_base",
        title: "stratigraphy.age_base",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "age_top",
        title: "stratigraphy.age_top",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "age_precision",
        title: "stratigraphy.age_precision",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "age_reference__id",
        title: "stratigraphy.age_reference__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "age_chronostratigraphy__id",
        title: "stratigraphy.age_chronostratigraphy__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "sort_within_parent",
        title: "stratigraphy.sort_within_parent",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "approved_ics",
        title: "stratigraphy.approved_ics",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "approved_esk",
        title: "stratigraphy.approved_esk",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "maaamet_kood",
        title: "stratigraphy.maaamet_kood",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "is_private",
        title: "stratigraphy.is_private",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "remarks",
        title: "stratigraphy.remarks",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_added",
        title: "stratigraphy.user_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_added",
        title: "stratigraphy.date_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_changed",
        title: "stratigraphy.user_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_changed",
        title: "stratigraphy.date_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "id",
        title: "stratigraphy.id",
        value: null,
        lookUpType: "icontains",
      },
    ],
    taxon: [
      {
        id: "taxon",
        title: "taxon.taxon",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "author_year",
        title: "taxon.author_year",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "taxon_epithet",
        title: "taxon.taxon_epithet",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "taxon_full_name",
        title: "taxon.taxon_full_name",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "taxon_original_name",
        title: "taxon.taxon_original_name",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "reference__id",
        title: "taxon.reference__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "parent__id",
        title: "taxon.parent__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "fossil_group__id",
        title: "taxon.fossil_group__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "synonym_of",
        title: "taxon.synonym_of",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "synonym_of_reference_id",
        title: "taxon.synonym_of_reference_id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "hierarchy_string",
        title: "taxon.hierarchy_string",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "rank__id",
        title: "taxon.rank__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "rank_original__id",
        title: "taxon.rank_original__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "type_taxon__id",
        title: "taxon.type_taxon__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "type_taxon_txt",
        title: "taxon.type_taxon_txt",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "stratigraphy_base__id",
        title: "taxon.stratigraphy_base__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "stratigraphy_top__id",
        title: "taxon.stratigraphy_top__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "in_estonia",
        title: "taxon.in_estonia",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "in_baltoscandia",
        title: "taxon.in_baltoscandia",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "is_fossil",
        title: "taxon.is_fossil",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "is_private",
        title: "taxon.is_private",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "is_valid",
        title: "taxon.is_valid",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "is_fossil_group",
        title: "taxon.is_fossil_group",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "sort",
        title: "taxon.sort",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "taxon_id_pbdb",
        title: "taxon.taxon_id_pbdb",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "taxon_id_plutof",
        title: "taxon.taxon_id_plutof",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "taxon_id_tol",
        title: "taxon.taxon_id_tol",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "taxon_id_eol",
        title: "taxon.taxon_id_eol",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "taxon_id_nrm",
        title: "taxon.taxon_id_nrm",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "remarks",
        title: "taxon.remarks",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "owner",
        title: "taxon.owner",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "is_authorized",
        title: "taxon.is_authorized",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_authorized",
        title: "taxon.user_authorized",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_added",
        title: "taxon.user_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_added",
        title: "taxon.date_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_changed",
        title: "taxon.user_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_changed",
        title: "taxon.date_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "id",
        title: "taxon.id",
        value: null,
        lookUpType: "icontains",
      },
    ],
    taxon_page: [
      {
        id: "taxon__id",
        title: "taxon_page.taxon__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "language",
        title: "taxon_page.language",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "on_frontpage",
        title: "taxon_page.on_frontpage",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "frontpage",
        title: "taxon_page.frontpage",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "frontpage_order",
        title: "taxon_page.frontpage_order",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "frontpage_title",
        title: "taxon_page.frontpage_title",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "title",
        title: "taxon_page.title",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "content",
        title: "taxon_page.content",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "author__id",
        title: "taxon_page.author__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "author_txt",
        title: "taxon_page.author_txt",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_txt",
        title: "taxon_page.date_txt",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "is_private",
        title: "taxon_page.is_private",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "link_wikipedia",
        title: "taxon_page.link_wikipedia",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_added",
        title: "taxon_page.user_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_added",
        title: "taxon_page.date_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_changed",
        title: "taxon_page.user_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_changed",
        title: "taxon_page.date_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "id",
        title: "taxon_page.id",
        value: null,
        lookUpType: "icontains",
      },
    ],
    visit: [
      {
        id: "visitor__id",
        title: "visit.visitor__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "visitor_free",
        title: "visit.visitor_free",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "visitor_institution__id",
        title: "visit.visitor_institution__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "visitor_country__id",
        title: "visit.visitor_country__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "host__id",
        title: "visit.host__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_arrived",
        title: "visit.date_arrived",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_left",
        title: "visit.date_left",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "purpose",
        title: "visit.purpose",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "collections_studied",
        title: "visit.collections_studied",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "items_studied",
        title: "visit.items_studied",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "remarks",
        title: "visit.remarks",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "database__id",
        title: "visit.database__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_added",
        title: "visit.user_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_added",
        title: "visit.date_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_changed",
        title: "visit.user_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_changed",
        title: "visit.date_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "id",
        title: "visit.id",
        value: null,
        lookUpType: "icontains",
      },
    ],
    web_news: [
      {
        id: "title_et",
        title: "web_news.title_et",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "title_en",
        title: "web_news.title_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "text_en",
        title: "web_news.text_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "text_et",
        title: "web_news.text_et",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "is_private",
        title: "web_news.is_private",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_added",
        title: "web_news.user_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_added",
        title: "web_news.date_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_changed",
        title: "web_news.user_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_changed",
        title: "web_news.date_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_expires",
        title: "web_news.date_expires",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "timestamp",
        title: "web_news.timestamp",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "id",
        title: "web_news.id",
        value: null,
        lookUpType: "icontains",
      },
    ],
    web_pages: [
      {
        id: "title_et",
        title: "web_pages.title_et",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "menu_title_et",
        title: "web_pages.menu_title_et",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "content_et",
        title: "web_pages.content_et",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "link_et",
        title: "web_pages.link_et",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "title_en",
        title: "web_pages.title_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "menu_title_en",
        title: "web_pages.menu_title_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "content_en",
        title: "web_pages.content_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "link_en",
        title: "web_pages.link_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "public",
        title: "web_pages.public",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "menu",
        title: "web_pages.menu",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "menu_bold",
        title: "web_pages.menu_bold",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "menu_color",
        title: "web_pages.menu_color",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "menu_fold",
        title: "web_pages.menu_fold",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "sort",
        title: "web_pages.sort",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "parent",
        title: "web_pages.parent",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "site",
        title: "web_pages.site",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "is_private",
        title: "web_pages.is_private",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user",
        title: "web_pages.user",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_inserted",
        title: "web_pages.date_inserted",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_expires",
        title: "web_pages.date_expires",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "timestamp",
        title: "web_pages.timestamp",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "id",
        title: "web_pages.id",
        value: null,
        lookUpType: "icontains",
      },
    ],
  },
  defaults: {
    accession: [
      "number",
      "date_signed",
      "agent_andis__agent",
      "agent_vottis__agent",
      "number_items",
      "description",
      "id",
    ],
    agent: [
      "id",
      "agent",
      "forename",
      "surename",
      "institution_name",
      "institution",
      "remarks",
      "type",
    ],
    collection: [
      "collection_id",
      "name",
      "name_long",
      "database__acronym",
      "link",
    ],
    deaccession: [
      "number",
      "date_signed",
      "agent_kandis",
      "number_items",
      "description",
      "id",
    ],
    loan: [
      "print",
      "id",
      "loan_number",
      "borrower",
      "project",
      "date_start",
      "date_end",
      "returned",
      "database",
    ],
    location: [
      "id",
      "location",
      "parent_location__location",
      "agent",
      "contents",
    ],
    rock: [
      "id",
      "name",
      "name_en",
      "formula_html",
      "rock_type",
      "rock_rank",
      "in_estonia",
      "in_portal",
      "link",
      "mindat_id",
    ],
    sarv_issue: [
      "replied",
      "id",
      "date_added",
      "from_user__username",
      "to_user__username",
      "title",
      "description",
      "url",
      "response",
    ],
    selection_series: ["id", "name", "remarks", "user_added"],
    stratigraphy: ["id", "stratigraphy", "type", "rank", "scope", "link"],
    taxon: [
      "id",
      "taxon",
      "author_year",
      "taxon_epithet",
      "parent__taxon",
      "fossil_group__taxon",
      "link",
    ],
    taxon_page: ["id", "taxon", "language", "title"],
    visit: [
      "id",
      "visitor",
      "visitor_country",
      "date_arrived",
      "date_left",
      "host",
    ],
    web_news: ["id", "title", "text", "is_private"],
    web_pages: ["id", "site", "title", "content", "public"],
  },
};

export default {
  namespaced: true,
  state,
  getters,
  actions,
  mutations,
};
