import getters from "@/store/modules/tableHeaders/getters";
import actions from "@/store/modules/tableHeaders/actions";
import mutations from "@/store/modules/tableHeaders/mutations";

// Todo: Change __ to . as vuetify support object notation in table headers (agent.id, specimen.specimen_full_name etc.)

const state = {
  accession: [
    {
      value: "number",
      text: "accession.number",
      show: true,
    },
    {
      value: "date_signed",
      text: "accession.date_signed",
      show: true,
    },
    {
      value: "agent_andis.agent",
      text: "accession.agent_andis__agent",
      show: true,
    },
    {
      value: "agent_vottis.agent",
      text: "accession.agent_vottis__agent",
      show: true,
    },
    {
      value: "number_items",
      text: "accession.number_items",
      show: true,
    },
    {
      value: "description",
      text: "accession.description",
      show: true,
    },
    {
      value: "id",
      text: "accession.id",
      show: true,
    },
    {
      value: "date_confirmed",
      text: "accession.date_confirmed",
      show: false,
    },
    {
      value: "agent_kinnitas.agent",
      text: "accession.agent_kinnitas__agent",
      show: false,
    },
    {
      value: "remarks",
      text: "accession.remarks",
      show: false,
    },
    {
      value: "user_added",
      text: "accession.user_added",
      show: false,
    },
    {
      value: "date_added",
      text: "accession.date_added",
      show: false,
    },
    {
      value: "user_changed",
      text: "accession.user_changed",
      show: false,
    },
    {
      value: "date_changed",
      text: "accession.date_changed",
      show: false,
    },
    {
      value: "database.acronym",
      text: "accession.database__acronym",
      show: false,
    },
  ],
  deaccession: [
    {
      value: "number",
      text: "deaccession.number",
      show: true,
    },
    {
      value: "date_signed",
      text: "deaccession.date_signed",
      show: true,
    },
    {
      value: "number_items",
      text: "deaccession.number_items",
      show: true,
    },
    {
      value: "description",
      text: "deaccession.description",
      show: true,
    },
    {
      value: "id",
      text: "deaccession.id",
      show: true,
    },
    {
      value: "date_confirmed",
      text: "deaccession.date_confirmed",
      show: false,
    },
    {
      value: "agent_kandis__agent",
      text: "deaccession.agent_kandis__agent",
      show: false,
    },
    {
      value: "agent_kandis__id",
      text: "deaccession.agent_kandis__id",
      show: false,
    },
    {
      value: "agent_kinnitas__id",
      text: "deaccession.agent_kinnitas__id",
      show: false,
    },
    {
      value: "agent_kinnitas__agent",
      text: "deaccession.agent_kinnitas__agent",
      show: false,
    },
    {
      value: "remarks",
      text: "deaccession.remarks",
      show: false,
    },
    {
      value: "user_added",
      text: "deaccession.user_added",
      show: false,
    },
    {
      value: "date_added",
      text: "deaccession.date_added",
      show: false,
    },
    {
      value: "user_changed",
      text: "deaccession.user_changed",
      show: false,
    },
    {
      value: "date_changed",
      text: "deaccession.date_changed",
      show: false,
    },
    {
      value: "database__id",
      text: "deaccession.database__id",
      show: false,
    },
    {
      value: "database__acronym",
      text: "deaccession.database__acronym",
      show: false,
    },
  ],
  loan: [
    {
      value: "print",
      text: "loan.print",
      sortable: false,
      show: true,
    },
    {
      value: "id",
      text: "loan.id",
      show: true,
    },
    {
      value: "loan_number",
      text: "loan.loan_number",
      show: true,
    },
    {
      value: "project",
      text: "loan.project",
      show: true,
    },
    {
      value: "date_start",
      text: "loan.date_start",
      show: true,
    },
    {
      value: "date_end",
      text: "loan.date_end",
      show: true,
    },
    {
      value: "returned",
      text: "loan.returned",
      show: true,
    },
    {
      value: "type__id",
      text: "loan.type__id",
      show: false,
    },
    {
      value: "type__value",
      text: "loan.type__value",
      show: false,
    },
    {
      value: "type__value_en",
      text: "loan.type__value_en",
      show: false,
    },
    {
      value: "borrower__id",
      text: "loan.borrower__id",
      show: false,
    },
    {
      value: "borrower__agent",
      text: "loan.borrower__agent",
      show: false,
    },
    {
      value: "borrower_institution",
      text: "loan.borrower_institution",
      show: false,
    },
    {
      value: "borrower_institution__agent",
      text: "loan.borrower_institution__agent",
      show: false,
    },
    {
      value: "loaner__id",
      text: "loan.loaner__id",
      show: false,
    },
    {
      value: "loaner__agent",
      text: "loan.loaner__agent",
      show: false,
    },
    {
      value: "date_signed",
      text: "loan.date_signed",
      show: false,
    },
    {
      value: "delivery_method__id",
      text: "loan.delivery_method__id",
      show: false,
    },
    {
      value: "delivery_method__value",
      text: "loan.delivery_method__value",
      show: false,
    },
    {
      value: "delivery_method__value_en",
      text: "loan.delivery_method__value_en",
      show: false,
    },
    {
      value: "deliverer__id",
      text: "loan.deliverer__id",
      show: false,
    },
    {
      value: "deliverer__agent",
      text: "loan.deliverer__agent",
      show: false,
    },
    {
      value: "delivery_remarks",
      text: "loan.delivery_remarks",
      show: false,
    },
    {
      value: "date_returned",
      text: "loan.date_returned",
      show: false,
    },
    {
      value: "special",
      text: "loan.special",
      show: false,
    },
    {
      value: "remarks",
      text: "loan.remarks",
      show: false,
    },
    {
      value: "user_added",
      text: "loan.user_added",
      show: false,
    },
    {
      value: "date_added",
      text: "loan.date_added",
      show: false,
    },
    {
      value: "user_changed",
      text: "loan.user_changed",
      show: false,
    },
    {
      value: "date_changed",
      text: "loan.date_changed",
      show: false,
    },
    {
      value: "database__id",
      text: "loan.database__id",
      show: false,
    },
    {
      value: "database__acronym",
      text: "loan.database__acronym",
      show: false,
    },
  ],
  location: [
    {
      value: "id",
      text: "location.id",
      show: true,
    },
    {
      value: "location",
      text: "location.location",
      show: true,
    },
    {
      value: "parent_location__location",
      text: "location.parent_location__location",
      show: true,
    },
    {
      value: "contents",
      text: "location.contents",
      show: true,
    },
    {
      value: "parent_location__id",
      text: "location.parent_location__id",
      show: false,
    },
    {
      value: "location_location",
      text: "location.location_location",
      show: false,
    },
    {
      value: "agent__id",
      text: "location.agent__id",
      show: false,
    },
    {
      value: "agent__agent",
      text: "location.agent__agent",
      show: false,
    },
    {
      value: "date_collected_free",
      text: "location.date_collected_free",
      show: false,
    },
    {
      value: "stratigraphy_free",
      text: "location.stratigraphy_free",
      show: false,
    },
    {
      value: "number_items",
      text: "location.number_items",
      show: false,
    },
    {
      value: "number_items_registered",
      text: "location.number_items_registered",
      show: false,
    },
    {
      value: "remarks",
      text: "location.remarks",
      show: false,
    },
    {
      value: "database__id",
      text: "location.database__id",
      show: false,
    },
    {
      value: "database__acronym",
      text: "location.database__acronym",
      show: false,
    },
    {
      value: "user_added",
      text: "location.user_added",
      show: false,
    },
    {
      value: "date_added",
      text: "location.date_added",
      show: false,
    },
    {
      value: "user_changed",
      text: "location.user_changed",
      show: false,
    },
    {
      value: "date_changed",
      text: "location.date_changed",
      show: false,
    },
  ],
  sarv_issue: [
    {
      value: "replied",
      text: "sarv_issue.replied",
      sortable: false,
      show: true,
    },
    {
      value: "date_added",
      text: "sarv_issue.date_added",
      show: true,
    },
    {
      value: "to_user__username",
      text: "sarv_issue.to_user__username",
      show: true,
    },
    {
      value: "title",
      text: "sarv_issue.title",
      show: true,
    },
    {
      value: "description",
      text: "sarv_issue.description",
      show: true,
    },
    {
      value: "url",
      text: "sarv_issue.url",
      show: true,
    },
    {
      value: "response",
      text: "sarv_issue.response",
      show: true,
    },
    {
      value: "from_user__id",
      text: "sarv_issue.from_user__id",
      show: false,
    },
    {
      value: "to_user__id",
      text: "sarv_issue.to_user__id",
      show: false,
    },
    {
      value: "user_added",
      text: "sarv_issue.user_added",
      show: false,
    },
    {
      value: "user_changed",
      text: "sarv_issue.user_changed",
      show: false,
    },
    {
      value: "date_changed",
      text: "sarv_issue.date_changed",
      show: false,
    },
    {
      value: "idfrom_user__username",
      text: "sarv_issue.idfrom_user__username",
      show: false,
    },
  ],
  taxon_page: [
    {
      value: "id",
      text: "taxon_page.id",
      show: true,
    },
    {
      value: "language",
      text: "taxon_page.language",
      show: true,
    },
    {
      value: "title",
      text: "taxon_page.title",
      show: true,
    },
    {
      value: "taxon__id",
      text: "taxon_page.taxon__id",
      show: false,
    },
    {
      value: "taxon__taxon",
      text: "taxon_page.taxon__taxon",
      show: false,
    },
    {
      value: "on_frontpage",
      text: "taxon_page.on_frontpage",
      show: false,
    },
    {
      value: "frontpage",
      text: "taxon_page.frontpage",
      show: false,
    },
    {
      value: "frontpage_order",
      text: "taxon_page.frontpage_order",
      show: false,
    },
    {
      value: "frontpage_title",
      text: "taxon_page.frontpage_title",
      show: false,
    },
    {
      value: "content",
      text: "taxon_page.content",
      show: false,
    },
    {
      value: "author__id",
      text: "taxon_page.author__id",
      show: false,
    },
    {
      value: "author__agent",
      text: "taxon_page.author__agent",
      show: false,
    },
    {
      value: "author_txt",
      text: "taxon_page.author_txt",
      show: false,
    },
    {
      value: "date_txt",
      text: "taxon_page.date_txt",
      show: false,
    },
    {
      value: "is_private",
      text: "taxon_page.is_private",
      show: false,
    },
    {
      value: "link_wikipedia",
      text: "taxon_page.link_wikipedia",
      show: false,
    },
    {
      value: "user_added",
      text: "taxon_page.user_added",
      show: false,
    },
    {
      value: "date_added",
      text: "taxon_page.date_added",
      show: false,
    },
    {
      value: "user_changed",
      text: "taxon_page.user_changed",
      show: false,
    },
    {
      value: "date_changed",
      text: "taxon_page.date_changed",
      show: false,
    },
  ],
  visit: [
    {
      value: "id",
      text: "visit.id",
      show: true,
    },
    {
      value: "date_arrived",
      text: "visit.date_arrived",
      show: true,
    },
    {
      value: "date_left",
      text: "visit.date_left",
      show: true,
    },
    {
      value: "visitor__id",
      text: "visit.visitor__id",
      show: false,
    },
    {
      value: "visitor__agent",
      text: "visit.visitor__agent",
      show: false,
    },
    {
      value: "visitor_free",
      text: "visit.visitor_free",
      show: false,
    },
    {
      value: "visitor_institution__id",
      text: "visit.visitor_institution__id",
      show: false,
    },
    {
      value: "visitor_institution__agent",
      text: "visit.visitor_institution__agent",
      show: false,
    },
    {
      value: "visitor_country__id",
      text: "visit.visitor_country__id",
      show: false,
    },
    {
      value: "visitor_country__value",
      text: "visit.visitor_country__value",
      show: false,
    },
    {
      value: "visitor_country__value_en",
      text: "visit.visitor_country__value_en",
      show: false,
    },
    {
      value: "host__id",
      text: "visit.host__id",
      show: false,
    },
    {
      value: "host__agent",
      text: "visit.host__agent",
      show: false,
    },
    {
      value: "purpose",
      text: "visit.purpose",
      show: false,
    },
    {
      value: "collections_studied",
      text: "visit.collections_studied",
      show: false,
    },
    {
      value: "items_studied",
      text: "visit.items_studied",
      show: false,
    },
    {
      value: "remarks",
      text: "visit.remarks",
      show: false,
    },
    {
      value: "database__id",
      text: "visit.database__id",
      show: false,
    },
    {
      value: "database__acronym",
      text: "visit.database__acronym",
      show: false,
    },
    {
      value: "user_added",
      text: "visit.user_added",
      show: false,
    },
    {
      value: "date_added",
      text: "visit.date_added",
      show: false,
    },
    {
      value: "user_changed",
      text: "visit.user_changed",
      show: false,
    },
    {
      value: "date_changed",
      text: "visit.date_changed",
      show: false,
    },
  ],
  web_news: [
    {
      value: "id",
      text: "web_news.id",
      show: true,
    },
    {
      value: "is_private",
      text: "web_news.is_private",
      show: true,
    },
    {
      value: "title_et",
      text: "web_news.title_et",
      show: false,
    },
    {
      value: "title_en",
      text: "web_news.title_en",
      show: false,
    },
    {
      value: "text_en",
      text: "web_news.text_en",
      show: false,
    },
    {
      value: "text_et",
      text: "web_news.text_et",
      show: false,
    },
    {
      value: "user_added",
      text: "web_news.user_added",
      show: false,
    },
    {
      value: "date_added",
      text: "web_news.date_added",
      show: false,
    },
    {
      value: "user_changed",
      text: "web_news.user_changed",
      show: false,
    },
    {
      value: "date_changed",
      text: "web_news.date_changed",
      show: false,
    },
    {
      value: "date_expires",
      text: "web_news.date_expires",
      show: false,
    },
    {
      value: "timestamp",
      text: "web_news.timestamp",
      show: false,
    },
  ],
  web_pages: [
    {
      value: "id",
      text: "web_pages.id",
      show: true,
    },
    {
      value: "site",
      text: "web_pages.site",
      show: true,
    },
    {
      value: "public",
      text: "web_pages.public",
      show: true,
    },
    {
      value: "title_et",
      text: "web_pages.title_et",
      show: false,
    },
    {
      value: "menu_title_et",
      text: "web_pages.menu_title_et",
      show: false,
    },
    {
      value: "content_et",
      text: "web_pages.content_et",
      show: false,
    },
    {
      value: "link_et",
      text: "web_pages.link_et",
      show: false,
    },
    {
      value: "title_en",
      text: "web_pages.title_en",
      show: false,
    },
    {
      value: "menu_title_en",
      text: "web_pages.menu_title_en",
      show: false,
    },
    {
      value: "content_en",
      text: "web_pages.content_en",
      show: false,
    },
    {
      value: "link_en",
      text: "web_pages.link_en",
      show: false,
    },
    {
      value: "menu",
      text: "web_pages.menu",
      show: false,
    },
    {
      value: "menu_bold",
      text: "web_pages.menu_bold",
      show: false,
    },
    {
      value: "menu_color",
      text: "web_pages.menu_color",
      show: false,
    },
    {
      value: "menu_fold",
      text: "web_pages.menu_fold",
      show: false,
    },
    {
      value: "sort",
      text: "web_pages.sort",
      show: false,
    },
    {
      value: "parent",
      text: "web_pages.parent",
      show: false,
    },
    {
      value: "is_private",
      text: "web_pages.is_private",
      show: false,
    },
    {
      value: "user",
      text: "web_pages.user",
      show: false,
    },
    {
      value: "date_inserted",
      text: "web_pages.date_inserted",
      show: false,
    },
    {
      value: "date_expires",
      text: "web_pages.date_expires",
      show: false,
    },
    {
      value: "timestamp",
      text: "web_pages.timestamp",
      show: false,
    },
  ],
  searchFields: {
    accession: [
      {
        id: "number",
        title: "accession.number",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_signed",
        title: "accession.date_signed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_confirmed",
        title: "accession.date_confirmed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "agent_andis__id",
        title: "accession.agent_andis__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "agent_vottis__id",
        title: "accession.agent_vottis__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "agent_kinnitas__id",
        title: "accession.agent_kinnitas__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "number_items",
        title: "accession.number_items",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "description",
        title: "accession.description",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "remarks",
        title: "accession.remarks",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_added",
        title: "accession.user_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_added",
        title: "accession.date_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_changed",
        title: "accession.user_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_changed",
        title: "accession.date_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "database__id",
        title: "accession.database__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "id",
        title: "accession.id",
        value: null,
        lookUpType: "icontains",
      },
    ],
    deaccession: [
      {
        id: "number",
        title: "deaccession.number",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_signed",
        title: "deaccession.date_signed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_confirmed",
        title: "deaccession.date_confirmed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "agent_kandis__id",
        title: "deaccession.agent_kandis__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "agent_kinnitas__id",
        title: "deaccession.agent_kinnitas__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "number_items",
        title: "deaccession.number_items",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "description",
        title: "deaccession.description",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "remarks",
        title: "deaccession.remarks",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_added",
        title: "deaccession.user_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_added",
        title: "deaccession.date_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_changed",
        title: "deaccession.user_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_changed",
        title: "deaccession.date_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "database__id",
        title: "deaccession.database__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "id",
        title: "deaccession.id",
        value: null,
        lookUpType: "icontains",
      },
    ],
    loan: [
      {
        id: "loan_number",
        title: "loan.loan_number",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_start",
        title: "loan.date_start",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_end",
        title: "loan.date_end",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "type__id",
        title: "loan.type__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "project",
        title: "loan.project",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "borrower__id",
        title: "loan.borrower__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "borrower_institution__id",
        title: "loan.borrower_institution__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "loaner__id",
        title: "loan.loaner__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_signed",
        title: "loan.date_signed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "delivery_method__id",
        title: "loan.delivery_method__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "deliverer__id",
        title: "loan.deliverer__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "delivery_remarks",
        title: "loan.delivery_remarks",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "returned",
        title: "loan.returned",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_returned",
        title: "loan.date_returned",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "special",
        title: "loan.special",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "remarks",
        title: "loan.remarks",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_added",
        title: "loan.user_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_added",
        title: "loan.date_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_changed",
        title: "loan.user_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_changed",
        title: "loan.date_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "database__id",
        title: "loan.database__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "id",
        title: "loan.id",
        value: null,
        lookUpType: "icontains",
      },
    ],
    location: [
      {
        id: "location",
        title: "location.location",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "parent_location__id",
        title: "location.parent_location__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "location_location",
        title: "location.location_location",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "contents",
        title: "location.contents",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "agent__id",
        title: "location.agent__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_collected_free",
        title: "location.date_collected_free",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "stratigraphy_free",
        title: "location.stratigraphy_free",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "number_items",
        title: "location.number_items",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "number_items_registered",
        title: "location.number_items_registered",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "remarks",
        title: "location.remarks",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "database__id",
        title: "location.database__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_added",
        title: "location.user_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_added",
        title: "location.date_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_changed",
        title: "location.user_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_changed",
        title: "location.date_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "id",
        title: "location.id",
        value: null,
        lookUpType: "icontains",
      },
    ],
    sarv_issue: [
      {
        id: "title",
        title: "sarv_issue.title",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "description",
        title: "sarv_issue.description",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "url",
        title: "sarv_issue.url",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "from_user__id",
        title: "sarv_issue.from_user__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "to_user__id",
        title: "sarv_issue.to_user__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "response",
        title: "sarv_issue.response",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_added",
        title: "sarv_issue.user_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_added",
        title: "sarv_issue.date_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_changed",
        title: "sarv_issue.user_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_changed",
        title: "sarv_issue.date_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "id",
        title: "sarv_issue.id",
        value: null,
        lookUpType: "icontains",
      },
    ],
    taxon_page: [
      {
        id: "taxon__id",
        title: "taxon_page.taxon__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "language",
        title: "taxon_page.language",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "on_frontpage",
        title: "taxon_page.on_frontpage",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "frontpage",
        title: "taxon_page.frontpage",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "frontpage_order",
        title: "taxon_page.frontpage_order",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "frontpage_title",
        title: "taxon_page.frontpage_title",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "title",
        title: "taxon_page.title",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "content",
        title: "taxon_page.content",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "author__id",
        title: "taxon_page.author__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "author_txt",
        title: "taxon_page.author_txt",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_txt",
        title: "taxon_page.date_txt",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "is_private",
        title: "taxon_page.is_private",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "link_wikipedia",
        title: "taxon_page.link_wikipedia",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_added",
        title: "taxon_page.user_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_added",
        title: "taxon_page.date_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_changed",
        title: "taxon_page.user_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_changed",
        title: "taxon_page.date_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "id",
        title: "taxon_page.id",
        value: null,
        lookUpType: "icontains",
      },
    ],
    visit: [
      {
        id: "visitor__id",
        title: "visit.visitor__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "visitor_free",
        title: "visit.visitor_free",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "visitor_institution__id",
        title: "visit.visitor_institution__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "visitor_country__id",
        title: "visit.visitor_country__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "host__id",
        title: "visit.host__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_arrived",
        title: "visit.date_arrived",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_left",
        title: "visit.date_left",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "purpose",
        title: "visit.purpose",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "collections_studied",
        title: "visit.collections_studied",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "items_studied",
        title: "visit.items_studied",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "remarks",
        title: "visit.remarks",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "database__id",
        title: "visit.database__id",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_added",
        title: "visit.user_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_added",
        title: "visit.date_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_changed",
        title: "visit.user_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_changed",
        title: "visit.date_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "id",
        title: "visit.id",
        value: null,
        lookUpType: "icontains",
      },
    ],
    web_news: [
      {
        id: "title_et",
        title: "web_news.title_et",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "title_en",
        title: "web_news.title_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "text_en",
        title: "web_news.text_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "text_et",
        title: "web_news.text_et",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "is_private",
        title: "web_news.is_private",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_added",
        title: "web_news.user_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_added",
        title: "web_news.date_added",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user_changed",
        title: "web_news.user_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_changed",
        title: "web_news.date_changed",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_expires",
        title: "web_news.date_expires",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "timestamp",
        title: "web_news.timestamp",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "id",
        title: "web_news.id",
        value: null,
        lookUpType: "icontains",
      },
    ],
    web_pages: [
      {
        id: "title_et",
        title: "web_pages.title_et",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "menu_title_et",
        title: "web_pages.menu_title_et",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "content_et",
        title: "web_pages.content_et",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "link_et",
        title: "web_pages.link_et",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "title_en",
        title: "web_pages.title_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "menu_title_en",
        title: "web_pages.menu_title_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "content_en",
        title: "web_pages.content_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "link_en",
        title: "web_pages.link_en",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "public",
        title: "web_pages.public",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "menu",
        title: "web_pages.menu",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "menu_bold",
        title: "web_pages.menu_bold",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "menu_color",
        title: "web_pages.menu_color",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "menu_fold",
        title: "web_pages.menu_fold",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "sort",
        title: "web_pages.sort",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "parent",
        title: "web_pages.parent",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "site",
        title: "web_pages.site",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "is_private",
        title: "web_pages.is_private",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "user",
        title: "web_pages.user",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_inserted",
        title: "web_pages.date_inserted",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "date_expires",
        title: "web_pages.date_expires",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "timestamp",
        title: "web_pages.timestamp",
        value: null,
        lookUpType: "icontains",
      },
      {
        id: "id",
        title: "web_pages.id",
        value: null,
        lookUpType: "icontains",
      },
    ],
  },
  defaults: {
    accession: [
      "number",
      "date_signed",
      "agent_andis__agent",
      "agent_vottis__agent",
      "number_items",
      "description",
      "id",
    ],
    deaccession: [
      "number",
      "date_signed",
      "agent_kandis",
      "number_items",
      "description",
      "id",
    ],
    loan: [
      "print",
      "id",
      "loan_number",
      "borrower",
      "project",
      "date_start",
      "date_end",
      "returned",
      "database",
    ],
    location: [
      "id",
      "location",
      "parent_location__location",
      "agent",
      "contents",
    ],
    sarv_issue: [
      "replied",
      "id",
      "date_added",
      "from_user__username",
      "to_user__username",
      "title",
      "description",
      "url",
      "response",
    ],
    taxon_page: ["id", "taxon", "language", "title"],
    visit: [
      "id",
      "visitor",
      "visitor_country",
      "date_arrived",
      "date_left",
      "host",
    ],
    web_news: ["id", "title", "text", "is_private"],
    web_pages: ["id", "site", "title", "content", "public"],
  },
};

export default {
  namespaced: true,
  state,
  getters,
  actions,
  mutations,
};
